### ISSUE TITLE
Let us choose a template. Customizations on every commits / iterations

### ISSUE THREAD

**Issue by rabishah** [Code4Nepal/iwalkfreely#3]
Hey guys, have a look at these links, we need to choose one of the templates to get started with the project?
- http://foundation.zurb.com/templates.html
- http://foundation.zurb.com/apps/page-templates.html

I like the news or magazines template present in  http://foundation.zurb.com/templates.html as it suits our project too. Open for suggestions.

**Comment by ravinepal** [comment]
@rabishah -- thank you for all you are doing :)

**Comment by Raashul** [comment]
I like the news or magazine template too.

**Comment by amitness** [comment]
I liked the News template and the [Agency](http://foundation.zurb.com/templates-previews-sites-f6/agency.html#) template.

**Comment by rabishah** [comment]
@Raashul @studenton Let's go with [News and Magazines](http://foundation.zurb.com/templates-previews-sites-f6/news-magazine.html) 

We will be customizing the template according to our need..

**Comment by Raashul** [comment]
I will get this done as soon as possible! Thanks for finalizing the template @rabishah @studenton.
