### ISSUE TITLE
Choose one visualizations library

### ISSUE THREAD

**Issue by rabishah** [Code4Nepal/iwalkfreely#9]
We need visualizations / charts / anything that emphasizes data in a succinct manner. 
- [x] [d3.js](https://github.com/d3/d3)
- [ ] [chartjs](http://www.chartjs.org/) 

Open for discussions.

**Comment by Raashul** [comment]
D3.js is famous and I think that can be a good start. Should we go with D3.js instead of waiting for others' response? @rabishah

**Comment by rabishah** [comment]
@Raashul @imsanju This one's a good tutorial to get your hands on d3 (version 4 is out 😄) Like you said, let's go with d3.js, has a vast community support too.

[d3 video tutorials](https://egghead.io/courses/build-interactive-javascript-charts-with-d3-v4?utm_source=drip&utm_medium=email&utm_campaign=d3-will-melt-your-gourd)

**Comment by rabishah** [comment]
d3.js !!!
